part of ReverseText;

class TextComponent
{

  FormElement   textForm;
  InputElement  textInput;
  InputElement  textOutput;
  LabelElement  textOutputLabel;
  InputElement  checkbox;
  ButtonElement reverseButton;

  TextComponent()
  {
    // use HTML5 querySelector for DOM retrieval
    textForm         = document.query('#textForm');
    textInput        = textForm.query('#inputText');
    textOutput       = textForm.query('#outputText');
    textOutputLabel  = textForm.query('#outputTextLabel');
    checkbox         = textForm.query('input[type=checkbox]');
    reverseButton    = textForm.query('button[type=submit]');

    // listen to checkbox state changes
    checkbox.$dom_addEventListener( 'change', handleEvent );

    // listen to reverse button clicks
    reverseButton.$dom_addEventListener( 'click', handleEvent );

    // Listen for input
    textInput.$dom_addEventListener( 'keyup', this.handleEvent );
  }

  /**
   * Set the palindrome indicator
   */
  void set isPalindrome ( bool izzit )
  {
    if (izzit) {
      textOutputLabel.innerHtml = "Palindrome Detected";
    } else {
      textOutputLabel.innerHtml = "Output Text";
    }
  }

  /**
   * Set the ouput fields text value
   */
  void set outputText ( String value )
  {
    isPalindrome = false;
    textOutput.value = value;
  }

  /**
   * Get the input fields text value
   */
  String get inputText
  {
    return textInput.value;
  }

  /**
   * Handle DOM Events this component is interested in.
   */
  void handleEvent( Event event )
  {
    switch( event.type )
    {
      /*
       * A keypress has been detected. If 'Reverse as I type'
       * is checked, dispatch a text changed event
       */
      case 'keyup':
        if (checkbox.checked) dispatchTextChangedEvent();
        break;

      /*
       * The TextComponent's reverse button has been clicked.
       * Prevent the form from submitting, and dispatch a
       * text changed event
       */
      case 'click':
        event.preventDefault();
        dispatchTextChangedEvent();
        break;
    }
  }

  /**
   * Add EventListeners to TextComponent. TextComponent will
   * dispatch only AppEvent.INPUT_TEXT_CHANGED events, but
   * you can still listen to other events generated by its
   * DOM elements as they propagate through #textForm.
   *
   * There is no reason to implement a removeEventListener in
   * this demo, as we never unregister the TextComponentMediator.
   */
  void addEventListener( String type, EventListener listener )
  {
    // delegate to #textForm
    textForm.$dom_addEventListener( type, listener );
  }

  /**
   * Dispatch an event
   */
  void dispatchTextChangedEvent()
  {
    Event event = document.$dom_createEvent("HTMLEvents");
    event.$dom_initEvent(AppEvents.INPUT_TEXT_CHANGED, true, true);
    textForm.dispatchEvent( event );
  }
}